<?xml version= "1.0" encoding= "UTF-8" standalone= "yes"?>

<!DOCTYPE Patient [

<!ELEMENT Patient (dob, email, doctors, treatments)>
	<!ATTLIST Patient name CDATA #REQUIRED>
	<!ELEMENT dob (#PCDATA)>
	<!ELEMENT email (#PCDATA)>
	<!ELEMENT doctors (doctor*)>
	<!ELEMENT doctor (email,speciality)>
	<!ATTLIST doctor name CDATA #REQUIRED>
	<!ELEMENT speciality (#PCDATA)>
	<!ELEMENT treatments (treatment*)>
	<!ELEMENT treatment (description,durationInDays)>
	<!ATTLIST treatment name CDATA #REQUIRED>
	<!ELEMENT description (#PCDATA)>
	<!ELEMENT durationInDays (#PCDATA)>
	
	]>
	
	
	
	
<Patient name="Sanfe">
	<dob>2003-07-07</dob>
	<email>sanfe@example.com</email>
	<doctors>
		<doctor name="Dr. Pepe">
			<email>pepe@example.com</email>
			<speciality>Urologist</speciality>
		</doctor>
		<doctor name="Dra. Maria">
			<email>maria@example.com</email>
			<speciality>Gynecologist</speciality>
		</doctor>
	</doctors>
	<treatments>
		<treatment name="Egg freezing">
			<description>Egg freezing, also known as oocyte cryopreservation, is a fertility preservation method where a womanâ€™s eggs are harvested, frozen, and stored for future use. This process allows women to preserve their fertility, offering the possibility to conceive at a later time when they are ready or when it is medically necessary.</description>
			<durationInDays>60</durationInDays>
		</treatment>
	</treatments>
</Patient>